theme = "lynx"
title = "JAlcocerT"
baseURL= "https://jalcocert.github.io/portfolio/"


enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "JAlcocerT Portfolio"
  headline = """
  From AI to Data Analytics
  """
  
  image = "fossengineer.png" 
  links = [
        { fossengineer = { href = "https://jalcocertech.xyz/", text = "Work with Me" } },
        { youtube = "https://www.youtube.com/@JAlcocerTech" },
    { linkedin = "https://www.linkedin.com/in/jalcocert/" },
    { medium = "https://medium.com/@jalcocert" },
    { github = "https://github.com/JAlcocerT/"},
        { GHPages = { href = "https://jalcocert.github.io/JAlcocerT", text = "My Learning Process" } },    

  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true